//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string Id { get; set; }
        public string CurseName { get; set; }
        public string CurseId { get; set; }
    }
}
